# Generated by Django 2.1.7 on 2020-01-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_sections',
            field=models.ManyToManyField(to='static_website.PageSection'),
        ),
    ]
