# Generated by Django 2.1.7 on 2020-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_website', '0002_auto_20200109_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='heading_icon',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
