# Generated by Django 2.1.7 on 2020-01-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_website', '0004_auto_20200109_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectiontext',
            name='col_length',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
