# Generated by Django 2.2 on 2019-06-22 02:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text_entry', tinymce.models.HTMLField()),
                ('date_of_submission', models.DateTimeField()),
                ('has_been_modified', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
    ]
