# Generated by Django 2.2.2 on 2019-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='date_updated',
            field=models.DateTimeField(default=None),
        ),
    ]
