# Generated by Django 2.1.7 on 2020-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='text_entry',
            field=models.TextField(),
        ),
    ]
