# Generated by Django 2.1.7 on 2020-01-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200105_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
